version: "3.9"

services:
  fastapi:
    build:
      context: .     # extra klasöründen çalıştığımız için burası nokta olmalı
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "5001:5001"
    volumes:
      - .:/app       # current extra dizinini /app olarak mount ediyoruz
    env_file:
      - .env
